import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, CheckCircle2, Clock3, Sparkles, Zap } from 'lucide-react'
import { getAnomalies, getMaintenance, getOverview, getTimeseries, optimize, explain } from '../lib/api'
import { Card } from '../components/ui/Card'
import { Badge } from '../components/ui/Badge'
import { MetricCard } from '../components/dashboard/MetricCard'
import { LoadChart } from '../components/dashboard/LoadChart'

export default function Dashboard(){
 const [overview,setOverview]=useState<any>(); const [series,setSeries]=useState<any[]>([]); const [anomalies,setAnomalies]=useState<any[]>([]); const [maintenance,setMaintenance]=useState<any[]>([]); const [opt,setOpt]=useState<any>(); const [ai,setAi]=useState<any>(); const [loading,setLoading]=useState(true)
 useEffect(()=>{(async()=>{try{const [o,s,a,m,op]=await Promise.all([getOverview(),getTimeseries(),getAnomalies(),getMaintenance(),optimize()]);setOverview(o);setSeries(s);setAnomalies(a);setMaintenance(m);setOpt(op)}finally{setLoading(false)}})()},[])
 const recent=useMemo(()=>series.slice(-8),[series])
 if(loading || !overview) return <div className="grid-bg grid min-h-[70vh] place-items-center"><div className="text-sm text-white/40">Loading plant telemetry...</div></div>
 const savingPct=opt ? Math.max(0,Math.round((1-opt.optimized_cost/opt.baseline_cost)*100)):0
 const askAI=async()=>{if(!opt) return; setAi(await explain({impact:opt.impact,schedule:opt.schedule,anomalies}))}
 return <div className="grid-bg min-h-full space-y-5 pb-10">
   <div className="grid grid-cols-2 gap-3 xl:grid-cols-5"><MetricCard label="Average Load" value={overview.avg_load_kw} unit="kW" delta="6.8%"/><MetricCard label="Peak Load" value={overview.peak_load_kw} unit="kW" delta="8.2%"/><MetricCard label="24H Energy" value={overview.energy_kwh.toLocaleString()} unit="kWh"/><MetricCard label="Monthly Savings" value={`₹${(overview.monthly_savings_inr/1000).toFixed(0)}k`} delta="12.4%"/><MetricCard label="Active Assets" value={overview.active_assets} unit="online"/></div>
   <div className="grid gap-5 xl:grid-cols-[1.45fr_.75fr]">
     <LoadChart data={series}/>
     <Card className="p-5"><div className="flex items-center justify-between"><div><h3 className="font-display text-sm font-semibold">AI Operations Brief</h3><p className="mt-1 text-xs text-white/30">Impact-aware explanation layer</p></div><div className="rounded-lg bg-acid/10 p-2 text-acid"><Sparkles size={16}/></div></div><div className="mt-5 rounded-xl border border-acid/10 bg-acid/[.035] p-4"><div className="flex items-start gap-3"><Zap size={17} className="mt-0.5 shrink-0 text-acid"/><div><div className="text-sm font-semibold">Potential peak reduction {opt ? Math.round(opt.impact.peak_reduction_kw):'--'} kW</div><p className="mt-1 text-xs leading-5 text-white/40">Move flexible batches away from high-tariff hours and keep the plant below the 680 kW operating cap.</p></div></div></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl border border-white/[.06] p-3"><div className="text-[10px] uppercase tracking-widest text-white/25">Cost saved</div><div className="mt-1 font-display text-lg">₹{opt?.impact.cost_saved_inr?.toLocaleString() ?? '--'}</div></div><div className="rounded-xl border border-white/[.06] p-3"><div className="text-[10px] uppercase tracking-widest text-white/25">ROI</div><div className="mt-1 font-display text-lg">{opt?.impact.roi_pct ?? '--'}%</div></div></div><button onClick={askAI} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-acid px-4 py-3 text-xs font-bold text-ink transition hover:brightness-105"><Sparkles size={14}/> Explain recommendations</button>{ai && <div className="mt-4 rounded-xl border border-white/[.06] bg-white/[.02] p-3 text-xs leading-5 text-white/60">{ai.summary}</div>}</Card>
   </div>
   <div className="grid gap-5 xl:grid-cols-[1fr_1fr]">
    <Card className="p-5"><div className="flex items-center justify-between"><div><h3 className="font-display text-sm font-semibold">Optimization Plan</h3><p className="mt-1 text-xs text-white/30">OR-Tools production scheduling</p></div><Badge tone="good">{savingPct}% lower cost</Badge></div><div className="mt-4 space-y-2">{opt?.schedule?.map((t:any)=><div key={t.name} className="grid grid-cols-[1fr_auto_auto] items-center gap-3 rounded-xl border border-white/[.05] bg-white/[.018] px-3 py-2.5"><div><div className="text-xs font-semibold">{t.name}</div><div className="mt-0.5 text-[10px] text-white/30">{t.power_kw} kW · {t.units} units</div></div><div className="text-right text-[11px] text-white/40">{String(t.start_hour).padStart(2,'0')}:00–{String(t.end_hour).padStart(2,'0')}:00</div><div className="rounded-lg bg-mint/8 px-2 py-1 text-[11px] font-semibold text-mint">₹{Math.round(t.cost).toLocaleString()}</div></div>)}</div></Card>
    <Card className="p-5"><div className="flex items-center justify-between"><div><h3 className="font-display text-sm font-semibold">Operational Alerts</h3><p className="mt-1 text-xs text-white/30">Anomaly + maintenance signal feed</p></div><Badge tone={anomalies.length?'warn':'good'}>{anomalies.length} anomalies</Badge></div><div className="mt-4 space-y-2">{anomalies.slice(0,4).map((a:any)=><div key={a.timestamp} className="flex items-start gap-3 rounded-xl border border-white/[.05] p-3"><div className="mt-0.5 rounded-lg bg-amber-300/10 p-1.5 text-amber-200"><ArrowUpRight size={14}/></div><div className="min-w-0"><div className="text-xs font-semibold">{new Date(a.timestamp).toLocaleString()}</div><p className="mt-1 text-[11px] leading-4 text-white/35">{a.message}</p></div><Badge tone={a.severity==='High'?'bad':'warn'}>{a.severity}</Badge></div>)}{maintenance.slice(0,2).map((m:any)=><div key={m.asset} className="flex items-center gap-3 rounded-xl border border-white/[.05] p-3"><div className="rounded-lg bg-white/[.04] p-1.5 text-white/45"><Clock3 size={14}/></div><div className="flex-1"><div className="text-xs font-semibold">{m.asset}</div><div className="mt-0.5 text-[11px] text-white/30">Maintenance {m.window}</div></div><CheckCircle2 size={15} className="text-mint"/></div>)}</div></Card>
   </div>
   <div className="text-[10px] text-white/20">Last telemetry sync: {new Date(overview.last_sync).toLocaleString()} · Demo telemetry is synthetic and should be replaced by plant data before production deployment.</div>
 </div>
}
